<li>
                  <div class="hot_img"><s></s><a class="fl" href="[field:url/]" title="[field:title/]" target="_blank"><img class="fl" src="[field:litpic/]" width="190" height="140" alt="[field:title/]" /></a></div>
                <div class="hot_tit"><a href="[field:url/]" title="[field:title/]"><span style="[field:color/]">[field:title/]</span></a></div>
                <div class="hot_txt">本季惊爆价：<span>[field:price/]</span>起</div>
              </li>