<div class="zx_list">
                        <ul>
                            <li><p class="p1"><span>网友：</span>[field:nickname/]</p><p class="p2">[field:addtime function="Mydate('Y-m-d H:i:s',@me)"/]</p></li>
                          <li><p class="p1"><span>咨询内容：</span></p><p class="txt">[field:content/]</p></li>
                          <li class="f50"><p class="p1"><span>客服回复：</span></p><p class="txt">先生/小姐：您好！[field:replycontent/]</p></li>
                        </ul>
                      </div>