<li>
                    <div class="hot_img"><s></s><a class="fl" href="[field:url/]" title="[field:title/]"><img class="fl" src="[field:lit240/]" width="190" height="140" alt="[field:title/]" /></a></div>
                    <div class="hot_tit"><a href="[field:url/]" target="_blank" title="[field:title/]">[field:title/]</a></div>
                    <div class="hot_txt">本季惊爆价：<span>&yen;[field:lineprice/]</span>起</div>
                  </li>