  {sline:getlinelist type="mdd" flag="recommend" row="2"}
                              <dl>
                                  <dt>
                                      <a class="fl" href="[field:url/]" target="_blank"><img class="fl" src="[field:lit160/]" width="90" height="70" alt="[field:title/]" title="[field:title/]" /></a>
                                  <h4><a href="[field:url/]" target="_blank">[field:title/]</a></h4>
                                  <p><b>[field:price2/]</b><label>满意度：<span class="color_f60">[field:satisfyscore/]</span></label><label>预订量：<span class="color_f60">[field:sellnum/]</span></label></p>
                                  </dt>
                                  <dd><span class="color_f60">产品特点：</span>[field:sellpoint/]</dd>
                              </dl>
                              {/sline:getlinelist}