<li [field:global.autoindex runphp='yes']if(@me%4==0)@me="class='mr_0'";else @me='';[/field:global.autoindex]>
                        <span class="dz_ico"><b>[field:discount/]折</b>优惠</span>
                        <a class="fl" href="[field:url/]" target="_blank"><img class="fl lazyimg" data-original="[field:litpic/]" alt="[field:title/]" width="220" height="124" /></a>
                        <a class="tit" href="[field:url/]" target="_blank">[field:title/]</a>
                        <span class="price">&yen;<b>[field:price/]</b></span>
                    </li>