<div class="con-l">
                    <s class="jh">精华</s>
                    <a class="fl" href="[field:url/]" target="_blank"><img class="fl" src="[field:litpic/]" width="295" height="190" title="[field:title/]" /></a>
                  <p class="p1">
                    <span class="sp1"><a href="/raiders/[field:pinyin/]/">[field:destname/]</a></span>
                    <span class="sp2">[field:shownum/]</span>
                    <span class="sp3">[field:commentnum/]</span>
                  </p>
                  <p class="p2"><a href="[field:url/]" target="_blank">[field:title/]</a></p>
                  <p class="p3">[field:content function="cutstr_html(@me,70)"/]<a href="[field:url/]" target="_blank">[详情]</a></p>
                </div>