<li class="post_item">
              	<dl>
                	<dt><a class="fl" href="[field:url/]" target="_blank"><img class="fl" src="[field:lit240/]" width="195" height="125" title="[field:title/]" alt="[field:title/]" /></a></dt>
                  <dd>
                  	<div class="tit">
                    	<a href="[field:url/]" target="_blank">[field:title/]</a>
                    	<div class="date">
                      	<span class="sp1">[field:shownum/]</span>
                        <span class="sp2">[field:commentnum/]</span>
                      </div>
                    </div>
                    <div class="txt">[field:content function="cutstr_html(@me,60)"/]</div>
                    [field:pinlun/]
                  </dd>
                </dl>
              </li>