<dl class="dl_list">
            	<dt><a class="fl" href="[field:url/]" target="_blank"><img class="fl" src="[field:lit240/]" width="218" height="130" alt="[field:litpic/]" /></a></dt>
              <dd class="dd1"><a href="[field:url/]" target="_blank">[field:title/]</a></dd>
              <dd class="dd2">
              	<span class="sp_1">¥[field:price/]</span>
                <span class="sp_2">[field:discount/]折</span>
                <a href="/tuan/book.php?tuanaid=[field:aid/]" target="_blank">抢购</a>
              </dd>
            </dl>