<div class="yx-rotaion">

                    <ul>
                      <li>
                        <a target="_blank" href="[field:url/]"><img class="lazyimg" data-original="[field:litpic/]" alt="[field:title/]" width="380" height="250"></a>
                      </li>
                    </ul>
                  </div>
                  <p class="tit"><a target="_blank" href="[field:url/]">[field:title/]</a></p>
                  <p class="txt">[field:content function="cutstr_html(@me,40)"/]</p>