<div id="categorys" class="categorys mdd_{sline:field.kindid/}">
            <div class="mc" id="_JD_ALLSORT" load="2" style="display: block;">
              {sline:getleftnav}
                <div class="item fore[field:global.autoindex/]" style="display: block;">
                    <span class="tit_bt">
                    <h3>
                      <a class="title_bt" href="/lines/[field:pinyin/]/">[field:categoryname/]</a>
                      [field:childpre/]
                    </h3>
                    <s></s>
                  </span>
                  <div class="i-mc" style="display: none; ">

                      <div class="subitem">
                          <div class="sub_left">
                              <dl class="hot_dl">
                                  <dt>热门线路</dt>
                                  <dd>
                                      [field:childnextall/]

                                  </dd>
                              </dl>
                              <dl class="sx_dl">
                                  <dt>游玩时间：</dt>
                                  <dd>
                                      [field:youwanshijian/]

                                  </dd>
                              </dl>
                              [field:shuxin/]

                              <dl class="sx_dl">
                                  <dt>价格区间：</dt>
                                  <dd>
                                      [field:jiage/]


                                  </dd>
                              </dl>
                          </div>
                          <div class="sub_rig">
                              [field:tjxianlu/]

                          </div>
                      </div>
                  </div>
                </div>
               {/sline:getleftnav}
            
              
              
            </div>
          </div>