<div class="room_balance">
                <table>
                    <tr class="room_th"><td align="center" width="22%">单房差</td><td align="center">购买数量</td><td align="center" width="26%">金额</td></tr>
                    <tr class="room_td"><td align="center">{sline:field.roombalance/}</td>
                        <td align="center">
                            <div class="num-increment">
                                <span class="down">-</span>
                            <input type="text" class="gm_num" id="roombalance_num" name="roombalancenum" readonly="" value="0">
                            <span class="up">+</span>
                            </div>
                        </td>
                        <td align="center" id="roombalance_total">0</td>
                    </tr>
                </table>
            </div>