<div class="tj_box">
                  <div class="tj_img"><s></s><a class="fl" href="[field:url/]" target="_blank"><img class="fl" src="[field:lit160/]" width="140" height="100" alt="说明" /></a></div>
                  <div class="tj_txt"><a href="[field:url/]" target="_blank">[field:title/]</a><span>[field:sellpoint/]</span></div>
                  <div class="tj_pre">
                      <span>[field:lineprice runphp='yes']
                               if(empty(@me))
                                  @me='电询';
                               else
                                  @me='&yen;'.@me.'起';
                          [/field:lineprice]</span>
                      <a href="[field:url/]" target="_blank">立即抢购</a>
                  </div>
              </div>