<li [field:global.autoindex runphp='yes']if(@me%3==0)@me="class='mr_0'";else @me='';[/field:global.autoindex]>
                          <a class="fl" href="[field:url/]" target="_blank"><img class="fl lazyimg" data-original="[field:litpic/]" alt="[field:title/]" width="294" height="162" /></a>
                          <a class="tit" href="[field:url/]" target="_blank">[field:title/]</a>
                          <span class="price">&yen;<b>[field:price3/]</b></span>
                      </li>